model:
  backbone: efficientnet_b0
  pretrained: True
  model_size: 384
  target_size: 2
  targets: ["fields","roads"]

data:
  base_path: ../data/train
  base_info: data.xlsx

training:
  logname: baseline-bceloss-f1score-input384-fold2
  kfold: 2
  seed: 100
  lr: 0.0001
  num_workers: 8
  max_epochs: 100
  batch_size: 32
  input_size: 384
  resume: False
  resume_epoch: 0
  weight_path: ""

valid:
  batch_size: 64
  weight_path: "logs/baseline-bceloss-f1score-input384-fold0/version_4/checkpoints/best_loss_ep53.ckpt"
  # "logs/baseline-bceloss-f1score-input384-fold2/version_0/checkpoints/best_loss_ep67.ckpt"
  # "logs/baseline-bceloss-f1score-input384-fold1/version_0/checkpoints/best_loss_ep30.ckpt"
  # "logs/baseline-bceloss-f1score-input384-fold0/version_4/checkpoints/best_loss_ep53.ckpt"

